FROM pldin601/musicloud-image

MAINTAINER Roman Lakhtadyr <roman.lakhtadyr@gmail.com>

ENV PHP_ENV development

WORKDIR /usr/app/

COPY cronfile /etc/cron.d/musicloud
RUN chmod 0644 /etc/cron.d/musicloud
