name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-nginx:
    name: Build nginx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: builder
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push master as latest
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder.outputs.name }}
          platforms: linux/amd64,linux/arm64
          tags: pldin601/musicloud-nginx:latest
          file: docker/nginx/Dockerfile
          push: true
  build-php-fpm:
    name: Build php-fpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: builder
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push master as latest
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder.outputs.name }}
          platforms: linux/amd64,linux/arm64
          tags: pldin601/musicloud-php-fpm:latest
          file: docker/php-fpm/Dockerfile
          push: true
  build-migration:
    name: Build migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: builder
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push master as latest
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.builder.outputs.name }}
          platforms: linux/amd64,linux/arm64
          tags: pldin601/musicloud-migration:latest
          file: docker/migration/Dockerfile
          push: true
